language: ruby
rvm:
- 2.3.1
before_install: gem install bundler -v 1.12.5
script:
- cd spec/dummy && RAILS_ENV=test bundle exec rake db:create db:migrate
- cd ../.. && bundle exec rspec spec
deploy:
  provider: rubygems
  api_key:
    secure: kkeEl/TFqK/jVVCMTis57AcKzjYwLb6OZYZiWtlfcmAwsSc0CgCRtMRDosSipOzzqrJCJk1Vq76mK9tQLFfTQpxdnyEKWSWM7JIvUEn/x4EmXJWsOBqN4ByV75+8kdGfFJEsALGI/IFIbtO3hf8NNcaJ2EPleMrkS0IiaRto66s=
  gem: admin_invitable
  on:
    tags: true
    repo: platanus/admin-invitable
